### ISSUE TITLE
pip install requierements pyHook error - clients error

### ISSUE THREAD

**Issue by Pvnic** [malwaredllc/byob#111]
This is what i get when i try to configurate the clients.py

```
> C:\Users\Root\Desktop\byob>python client.py 127.0.0.1 8080 --freeze
> 
> 
> 88                                  88
> 88                                  88
> 88                                  88
> 88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
> 88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
> 88       d8  `8b   d8'  8b       d8 88       d8
> 88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
> 8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
>                 d8'
>                d8'
> 
> 
> [>] Modules
>         Adding modules...  (3 modules added to client)
> 
> [>] Imports
>         Adding imports...- (25 imports from 3 modules)
> 
> [>] Payload
>         Uploading payload... (hosting payload at: http://127.0.0.1:8081///payloads/tyH.py)
> 
> [>] Stager
>         Uploading stager... - (hosting stager at: http://127.0.0.1:8081///stagers/tyH.py)
> 
> [>] Dropper
>         Writing dropper... (338 bytes written to byob_tyH.py)
>         Compiling executable...
> 332 INFO: PyInstaller: 3.3.1
> 332 INFO: Python: 2.7.12
> 334 INFO: Platform: Windows-10-10.0.17763
> 337 INFO: UPX is not available.
> Traceback (most recent call last):
>   File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "C:\Python27\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 101, in <module>
>     run()
>   File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 94, in run
>     run_build(pyi_config, spec_file, **vars(args))
>   File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
>     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
>   File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
>     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
>   File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
>     exec(text, spec_namespace)
>   File "<string>", line 2, in <module>
>   File "C:\Python27\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 54, in __init__
>     self._aesmod = import_aes(get_crypto_hiddenimports())
>   File "C:\Python27\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 37, in get_crypto_hiddenimports
>     import_aes(modname)
>   File "C:\Python27\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 21, in import_aes
>     return __import__(module_name, fromlist=[module_name.split('.')[-1]])
> ImportError: No module named Crypto.Cipher.AES
```

And when i run "pip install -r requirements.txt"

```
> C:\Users\Root\Desktop\byob>pip install -r requirements.txt
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
> Requirement already satisfied: mss==3.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1)) (3.3.0)
> Requirement already satisfied: WMI==1.4.9 in c:\python27\lib\site-packages (from -r requirements.txt (line 2)) (1.4.9)
> Requirement already satisfied: numpy==1.15.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 3)) (1.15.2)
> Requirement already satisfied: pyxhook==1.0.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 4)) (1.0.0)
> Requirement already satisfied: twilio==6.14.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 5)) (6.14.0)
> Requirement already satisfied: colorama==0.3.9 in c:\python27\lib\site-packages (from -r requirements.txt (line 6)) (0.3.9)
> Requirement already satisfied: requests==2.20.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 7)) (2.20.0)
> Requirement already satisfied: PyInstaller==3.3.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 8)) (3.3.1)
> Requirement already satisfied: opencv-python==3.4.3.18 in c:\python27\lib\site-packages (from -r requirements.txt (line 9)) (3.4.3.18)
> Collecting pyHook==1.5.1 (from -r requirements.txt (line 10))
>   Could not find a version that satisfies the requirement pyHook==1.5.1 (from -r requirements.txt (line 10)) (from versions: )
> No matching distribution found for pyHook==1.5.1 (from -r requirements.txt (line 10))
> 
```
Ty Guys !!

**Comment by malwaredllc** [comment]
For the first issue, the `requirements.txt` file was missing a certain cryptography package required by PyInstaller to be able to encrypt the Python code compiled into binary executables. I just pushed changes to `requirements.txt` that should fix this issue before it occurs (commit 90013f3b96f376d83791b93304957adee632d466), so if you try again with a fresh install it should work.

For the second issue, try running `pip install pyHook` without specifying the version number and let me know if that resolves it.

**Comment by Pvnic** [comment]
Hi ! I still get the second issue
« C:\Users\Thomas Michel\Desktop\byob>pip install pyHook
Collecting pyHook
  Could not find a version that satisfies the requirement pyHook (from versions: )
No matching distribution found for pyHook »

I am using python 2.7.15

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Malwared LLC <notifications@github.com>
Envoyé : Tuesday, April 16, 2019 9:56:41 PM
À : malwaredllc/byob
Cc : Pvnic; Author
Objet : Re: [malwaredllc/byob] pip install requierements pyHook error - clients error (#111)


For the first issue, the requirements.txt file was missing a certain cryptography package required by PyInstaller to be able to encrypt the Python code compiled into binary executables. I just pushed changes to requirements.txt that should fix this issue before it occurs (commit 90013f3<https://github.com/malwaredllc/byob/commit/90013f3b96f376d83791b93304957adee632d466>), so if you try again with a fresh install it should work.

For the second issue, try running pip install pyHook without specifying the version number and let me know if that resolves it.

**Comment by malwaredllc** [comment]
Ok try this:

1. Download the pyHook module as a wheel file [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook) 

- make sure to download the correct pyHook module for your version of Python (i.e. 2.7.15) 
- make sure to download 32-bit version if you have a 32-bit system or 64-bit version if you have a 64-bit system

2. Open the command-prompt and navigate to the folder where you downloaded the pyHook module

3. Install the module with pip (e.g. `pip install pyHook-1.5.1-cp27-none-win32.whl`)

**Comment by Pvnic** [comment]
This worked thank you
But i still got issues with it if you can anwser me this is the error that pop just after running client.py



« C:\Users\Thomas Michel\Desktop\byob-master (1)\byob-master\byob>py client.py 127.0.0.1 80 --freeze


88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[>] Modules
        Adding modules...  (3 modules added to client)

[>] Imports
        Adding imports...- (25 imports from 3 modules)

[>] Payload
        Uploading payload... -(hosting payload at: http://127.0.0.1:81///payloads/n8A.py)

[>] Stager
        Uploading stager...  (hosting stager at: http://127.0.0.1:81///stagers/n8A.py)

[>] Dropper
        Writing dropper...  (334 bytes written to byob_n8A.py)
        Compiling executable...
289 INFO: PyInstaller: 3.3.1
289 INFO: Python: 2.7.15
292 INFO: Platform: Windows-10-10.0.17134
295 INFO: wrote C:\Users\Thomas Michel\Desktop\byob-master (1)\byob-master\byob\Thomas.spec
298 INFO: UPX is not available.
Traceback (most recent call last):
 File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 101, in <module>
    run()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 162, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script 'C:\Users\Thomas Michel\Desktop\byob-master (1)\byob-master\byob\Michel\Desktop\byob-master' not found »

I also gonna post it on GitHub
Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Malwared LLC <notifications@github.com>
Envoyé : Thursday, April 18, 2019 11:09:53 PM
À : malwaredllc/byob
Cc : Pvnic; Author
Objet : Re: [malwaredllc/byob] pip install requierements pyHook error - clients error (#111)


Ok try this:

  1.  Download the pyHook module as a wheel file here<https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook>

  *   make sure to download the correct pyHook module for your version of Python (i.e. 2.7.15)
  *   make sure to download 32-bit version if you have a 32-bit system or 64-bit version if you have a 64-bit system

  1.  Open the command-prompt and navigate to the folder where you downloaded the pyHook module

  2.  Install the module with pip (e.g. pip install pyHook-1.5.1-cp27-none-win32.whl)

**Comment by malwaredllc** [comment]
Original issue has been resolved, this now duplicates issue #114.
