### ISSUE TITLE
Failed generating exe payload

### ISSUE THREAD

**Issue by DerDanny** [malwaredllc/byob#361]
The exe payload cant be created. I would like to fix it but I dont know

terminal shows:

b'0044:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\\\\\.\\\\DISPLAY1".'

I have no problems with generating a python payload.

**Comment by thisisme-url** [comment]
I have the same issue. Does it stop there in the terminal or does it advance after this line: 

b'0044:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1". 

?

In my case the terminal shows the same error but still advances until this error line:

Exception in api.routes.payload.payload_generate: [Errno 2]

**Comment by rclarsfull** [comment]
exact same behavior for me. Im using a kali vm.

**Comment by Aterox-os** [comment]
You cant compile a .exe on a linux system. You have to install BYOB on windows. 

When you installed it correctly you have to go in
**\byob-master\byob after that: python3 client.py <IP ADRESS OF THE ATTACKER PC> <PORT> --freeze.**

If you get an error add after the --freeze command --debug

**Comment by garsh1** [comment]
@Aterox-os that is not correct. 

This error has been solved, the exe payloads will now generate on Linux systems. Please uninstall docker, update to the latest version or Byob, and rerun startup.sh.

**Comment by skill3472** [comment]
The issue is still there. Ubuntu server can not generate Windows executables. Everything is updated and just installed.
